# Generated by Django 2.0.4 on 2018-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180409_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='emailid',
            field=models.CharField(max_length=100),
        ),
    ]
