# Generated by Django 2.0.4 on 2018-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180409_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='emailid',
        ),
        migrations.AddField(
            model_name='signup',
            name='mailid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
