# Generated by Django 2.0.4 on 2018-04-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180409_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='mailid',
        ),
    ]
