# Generated by Django 2.0.4 on 2018-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_signup_mailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
