# Generated by Django 2.0.4 on 2018-04-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180409_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
    ]
