# Generated by Django 2.0.4 on 2018-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180409_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='emailid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
