# Generated by Django 2.0.4 on 2018-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180409_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
