# Generated by Django 2.0.4 on 2018-04-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Signup')),
            ],
        ),
    ]
