# Generated by Django 2.0.4 on 2018-04-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='signup',
        ),
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
