# Generated by Django 2.0.4 on 2018-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180409_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='security_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='security_question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
