# Generated by Django 2.0.4 on 2018-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180410_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
