# Generated by Django 2.0.4 on 2018-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180410_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='username',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
