# Generated by Django 2.0.4 on 2018-04-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180410_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
