# Generated by Django 2.0.4 on 2018-04-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
